// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzXsOGWZO1OiJwoIphfCF7BOY4ehfUUdM',
    appId: '1:526055588541:web:ed49913ff9f90551b8add4',
    messagingSenderId: '526055588541',
    projectId: 'krishi-setu-2f87f',
    authDomain: 'krishi-setu-2f87f.firebaseapp.com',
    storageBucket: 'krishi-setu-2f87f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC71xI1gwjCTEOvuTHoxl10nE5amB0DSX0',
    appId: '1:526055588541:android:da64277c9ab5ef84b8add4',
    messagingSenderId: '526055588541',
    projectId: 'krishi-setu-2f87f',
    storageBucket: 'krishi-setu-2f87f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqE4aQt0vjpb1dILGqg4bV-_cdeYrfY68',
    appId: '1:526055588541:ios:4fffae03c0a44721b8add4',
    messagingSenderId: '526055588541',
    projectId: 'krishi-setu-2f87f',
    storageBucket: 'krishi-setu-2f87f.appspot.com',
    iosBundleId: 'com.example.krishiSetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqE4aQt0vjpb1dILGqg4bV-_cdeYrfY68',
    appId: '1:526055588541:ios:4fffae03c0a44721b8add4',
    messagingSenderId: '526055588541',
    projectId: 'krishi-setu-2f87f',
    storageBucket: 'krishi-setu-2f87f.appspot.com',
    iosBundleId: 'com.example.krishiSetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzXsOGWZO1OiJwoIphfCF7BOY4ehfUUdM',
    appId: '1:526055588541:web:c8b8c1b37e519041b8add4',
    messagingSenderId: '526055588541',
    projectId: 'krishi-setu-2f87f',
    authDomain: 'krishi-setu-2f87f.firebaseapp.com',
    storageBucket: 'krishi-setu-2f87f.appspot.com',
  );
}
